image: Visual Studio 2017

environment:
  matrix:
    - qt: 5.12\msvc2017_64
    - qt: 5.12\mingw73_64

install:
  # download jom for MSVC build
  - if /i not %qt:msvc=% == %qt% (
      curl -O -J -L -s -S http://download.qt.io/official_releases/jom/jom.zip
      & 7z x *.zip -oC:\jom > nul
      & del *.zip
    )

before_build:
  - set src_path=%cd%
  - call "C:\Qt\%qt%\bin\qtenv2.bat"
  - if /i not %qt:msvc=% == %qt% call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if /i not %qt:msvc=% == %qt% set PATH=C:\jom;%PATH%
  - cd %src_path%

build_script:
  - qmake -config release hello.pro
  - if /i not %qt:msvc=% == %qt% jom
  - if /i not %qt:mingw=% == %qt% mingw32-make -j4

test: off
