language: cpp

os:
  - linux
  - osx

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal

osx_image: 
  - xcode11.3
  - xcode11.6
  - xcode12.2

addons:
  apt:
    packages:
      - qtbase5-dev
      - cmake

  homebrew:
    packages:
      - qt
      - cmake

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5" ..
  - cmake --build . --parallel 2
