language: cpp

os:
  - linux
  - osx

dist: focal
osx_image: xcode11.6

addons:
  apt:
    packages:
      - qtbase5-dev
      - qttools5-dev-tools

  homebrew:
    packages:
      - qt

before_script:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew link --force qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export QMAKE_ARGS="-qt=5"; fi

script:
  - qmake ${QMAKE_ARGS} -config release hello.pro
  - make -j2
